mod day_1;
mod day_10;
mod day_11;
mod day_12;
mod day_13;
mod day_14;
mod day_15;
mod day_16;
mod day_17;
mod day_18;
mod day_19;
mod day_2;
mod day_3;
mod day_4;
mod day_5;
mod day_6;
mod day_7;
mod day_8;
mod day_9;

pub fn print_all_answers() {
    println!("2017");
    println!("1. {}", day_1::answers());
    println!("2. {}", day_2::answers());
    println!("3. {}", day_3::answers());
    println!("4. {}", day_4::answers());
    println!("5. {}", day_5::answers());
    println!("6. {}", day_6::answers());
    println!("7. {}", day_7::answers());
    println!("8. {}", day_8::answers());
    println!("9. {}", day_9::answers());
    println!("10. {}", day_10::answers());
    println!("11. {}", day_11::answers());
    println!("12. {}", day_12::answers());
    println!("13. {}", day_13::answers());
    println!("14. {}", day_14::answers());
    println!("15. {}", day_15::answers());
    println!("16. {}", day_16::answers());
    println!("17. {}", day_17::answers());
    println!("18. {}", day_18::answers());
    println!("19. {}", day_19::answers());
    println!("");
}
